#pragma once

#include <stdbool.h>

#define POWER_MANAGER_BUTTON_PIN 21
#define POWER_MANAGER_POWER_SWITCH_PIN 22
#define POWER_MANAGER_STATUS_LED_PIN 27

#define POWER_MANAGER_TASK_INTERVAL_MS 500

#define POWER_MANAGER_POWER_ON_DELAY_MS (2 * 1000)
#define POWER_MANAGER_POWER_OFF_DELAY_MS (2 * 1000)
#define POWER_MANAGER_AUTO_POWER_OFF_DELAY_MS (5 * 60 * 1000)

#define POWER_MANAGER_POWER_ON_LED_BLINK_TIME_MS (2 * 1000)

#define POWER_MANAGER_WATCHDOG_TIMEOUT_MS (5 * 1000)

#define POWER_MANAGER_BATTERY_CHECK_INTERVAL_MS (10 * 1000)
#define POWER_MANAGER_BATTERY_LOW_SOC 20
#define POWER_MANAGER_BATTERY_CRITICAL_SOC 5

void power_manager_init(void);
void power_manager_set_connected(bool connected);

void power_manager_task(void);
